name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Testing - Components & E2E
        uses: cypress-io/github-action@v6
        with:
            component: true
            command: npm run test
            start: npm run dev
            wait-on: http://localhost:3000
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "fake deploy because heroku is not free anymore
          and Vercel have its own in-platform deploy hehehe"
